List categoryMapList = [
  {"name": "Abrasives", "imagePath": "assets/images/categories/Group 5784.png"}, //TODO change the image, causes problem when color is changed on postAdCategory() page
  {"name": "Bearings", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Circuit Breakers", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Cutting Tools", "imagePath": "assets/images/categories/welder 1.png"},
  {"name": "Electrical Fittings", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Electrical Heaters", "imagePath": "assets/images/categories/heating 1.png"},
  {"name": "Electrical Switches", "imagePath": "assets/images/categories/switch 1.png"},
  {"name": "Fastner Switches", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Filters", "imagePath": "assets/images/categories/air-filter 1.png"},
  {"name": "Flanges", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Gearbox", "imagePath": "assets/images/categories/package-box 1.png"},
  {"name": "Hardware", "imagePath": "assets/images/categories/screw 1.png"},
  {"name": "Hose Pipe", "imagePath": "assets/images/categories/tube 1.png"},
  {"name": "Hydraulic Accessories", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Hydraulic Cylinders", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Industrial Belts & V Belts", "imagePath": "assets/images/categories/timing-belt 1.png"},
  {"name": "Insulation Material", "imagePath": "assets/images/categories/insulation 1.png"},
  {"name": "Lifting Equipments", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Lifting Hooks, Chains & Clamps", "imagePath": "assets/images/categories/hook 1.png"},
  {"name": "Measuring Instruments", "imagePath": "assets/images/categories/caliper 1.png"},
  {"name": "Motors", "imagePath": "assets/images/categories/electric-motor 1.png"},
  {"name": "Office Equipments", "imagePath": "assets/images/categories/fax 1.png"},
  {"name": "Oils & Lubricants", "imagePath": "assets/images/categories/oiler 1.png"},
  {"name": "Packaging Material", "imagePath": "assets/images/categories/box (1) 1.png"},
  {"name": "Paint", "imagePath": "assets/images/categories/paint 1.png"},
  {"name": "Pipe Fittings", "imagePath": "assets/images/categories/plumbing 1.png"},
  {"name": "Pipes", "imagePath": "assets/images/categories/tubes 1.png"},
  {"name": "Plates", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Plumbing Material", "imagePath": "assets/images/categories/wrench 1.png"},
  {"name": "Pneumatic Accessories", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Pneumatics Cylinders", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Ropes", "imagePath": "assets/images/categories/rope 1.png"},
  {"name": "Rubber Parts", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Safety Equipments", "imagePath": "assets/images/categories/helmet 1.png"},
  {"name": "Sheets", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Springs", "imagePath": "assets/images/categories/vending-machine 1.png"},
  {"name": "Tools", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Trolley Wheels", "imagePath": "assets/images/categories/bearing 1.png"},
  {"name": "Valves", "imagePath": "assets/images/categories/valve 1.png"},
  {"name": "Welding Consumables", "imagePath": "assets/images/categories/welding 1.png"},
  {"name": "Wires & Cables", "imagePath": "assets/images/categories/wire 1.png"},
  {"name": "Wire Mesh & Gratings", "imagePath": "assets/images/categories/bearing 1.png"},
];